# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-12 23:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import otp.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('contact_number', models.CharField(help_text=b'The mobile number to deliver tokens to.', max_length=16)),
                ('key', models.CharField(default=otp.utils.get_random_key, max_length=4)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='otp',
            unique_together=set([('key', 'contact_number')]),
        ),
    ]
